GeertJohan/go.rice

- appended.go
- box.go
- virtual.go
- walk.go
I'm trying to use https://github.com/inconshreveable/go-update and I ran into the issue where go.rice had open files.. so I couldn't rename the running executable under Windows.
This fixes it.
> Make sure we close the open files each time.

- appended.go
This fixes the "Assignment count mismatch: 3 = 2" compilation error introduced in 368fb46cb7fec929d69b5c865baa81b5598b3966
Now the situation is back to what it was before that pull-request: the zip file does not get closed, but at least it compiles.
Would you want me to create a wercker CI configuration so that the code is compiled and tested after each commit to master?
> fix "assignment count mismatch: 3 = 2"

- wercker.yml
Wercker is an online CI system, it is free for private/public repos while in beta. Once out of beta it will stay free for open-source projects  (see: https://twitter.com/Wercker/status/486148925376974848 )
Here is a wercker configuration that will build / test / vet / lint code whenever code is pushed to the repository (note that linting problems don't break the build).
Pull-Requests will be automatically built as well.
After merging the PR you should register on wercker.com and add the app for the CI to start.
> wercker configuration

- box.go
The `Bytes()` implementation breaks under Windows.  This `ReadFile` could eventually simply replace it. It also is more similar to the stdlib's `ioutil.ReadFile`.
> `ReadFile()` implementation that works on Windows.

- appended.go
kardianos/osext has moved to github and the build breaks with go 1.4 canonical imports
> fix import of kardianos/osext

- box.go
- config.go
Whit `rice.LocateFS`, `rice.FindBox` would lookup box directory from the package path where `FindBox` is called, this is fine when your main program use `github.com/GeertJohan/go.rice` directly. 
But it has trouble when you use `github.com/GeertJohan/go.rice` in your own packages, and then import your own package from the main program.
`rice.LocateWorkingDirectory` support is a minor change to support looking up box directory from the binary working directory :smile:
> add rice.LocateWorkingDirectory support

- README.md
- rice/embed-go.go
- rice/templates.go
The current file name generation is brittle, and breaks in a number of
corner-cases - see issue #67.
This patch refactors the way embedded files are generated. Instead of
generating one file per box, we generate a single file per package, with a
fixed name (rice-box.go), which includes one init() method per box. This
eliminates pretty much all the ambiguity and complexity around file name
generation.
Fixes #67
> Change embed-go to generate a single source file per package

- rice/embed-go.go
- rice/embed-syso.go
Hi,
I discovered a problem related to rebuilding embedded resources. When your re-embed the same files, the generated rice-box.go file changes - the box's Time attribute is being set to time.Now() value, which in fact is wrong, because it is not touched. 
I decided to change its value to modification time and open a pull request with those changes.
Happy New Year,
Marcin
> Real modification time of embedded boxes

- rice/find.go
- rice/find_test.go
- rice/templates.go
This very small change fixes memory usage during compilation. When compiling the swagger ui 1.2 dist folder it required up to 4GB of RAM during compilation. Now it's negligble. The underlying issue in the compiler is here: https://github.com/golang/go/issues/14082
This also has the side effect of creating smaller generated files.
> Fix huge memory usage during compilation of embed-go files, fix referencing via variable using non standard config

- rice/append.go
Make sure to close the zip file and remove it from the filesystem after
usage.
> Fix leaking zip file when appending boxes to an executable

- .gitignore
- rice/append.go
- wercker.yml
> use zipWriter.SetOffset instead of "zip -A"

- rice/embed-go.go
Error returned by writeBoxesGo function was not handled.
> Fix bug in embed-go

- rice/templates.go
This stops goimport from persistently trying to reformat `rice-box.go` files by grouping imports the way it expects. We use a combination of `goimport` and `rice embed-go` to embed data in binaries, and our CI "check that rice-box.go files are up to date" script causes goimport errors; running `goimport`, in turn, causes the files to be modified back the next time we run `rice`.
> goimport-friendly template.

- go.mod
- go.sum
- [go modules](https://github.com/golang/go/wiki/Modules) will be enabled in 1.13
- `go mod tidy` was also run to include required dependencies
- if you would like to only consume valid releases, this can block on:
- this will remove all `// indirect` dependencies
- this could also be done later
- after merge it would be nice if you would tag this repo: e.g. `v1.0.0`
- this will allow consumers something more consistent and readable than `v0.0.0-20181229203832-0af3f3b09a0a`
> add mod file

- embedded/embedded.go
I came across a recursive link to the root directory of `embedded.EmbedTypeSyso` `embedded.EmbeddedBox`s. More specifically, for `embedded.EmbeddedBox.Filename == ""` `embedded.EmbeddedBox.Dirs` contains a reference to itself. 
This causes `Box.Walk` to terminate early.
The flaw appears to be a missing check in `embedded.EmbeddedBox.Link` where, unlike [`rice.writeBoxesGo`](https://github.com/GeertJohan/go.rice/blob/0af3f3b09a0a8b391f63ab52ba5ab50f84fabd30/rice/embed-go.go#L89) and [`rice.operationEmbedSyso`](https://github.com/GeertJohan/go.rice/blob/0af3f3b09a0a8b391f63ab52ba5ab50f84fabd30/rice/embed-syso.go#L130), root detection [`path == 0`] does not occur.
> prevent recursive structure in embedded.EmbeddedBox.Link

- embedded/embedded.go
When consuming this library in a command line binary, I had trouble using `os.Stdout` programmatically, due to the extra output from `go.rice` generated by during the `init` phase.
`embedded.EmbeddedBox.Link` prints using [`fmt.Println`](https://github.com/GeertJohan/go.rice/blob/0af3f3b09a0a8b391f63ab52ba5ab50f84fabd30/embedded/embedded.go#L28)
I prefer libraries to not interact with `os.Stdout` as it is a side effect that is not usable by consumers. Furthermore, while this pattern is fine for things like webservers that have logs for `os.Stdout`, it is incompatible with command line utilities that use `os.Stdout` for message passing.
If you do like this functionality, it could be hidden behind a [`rice.verbosef`](https://github.com/GeertJohan/go.rice/blob/master/rice/main.go#L83)-like …
> remove print from embedded.EmbeddedBox.Link

- walk.go
Change in line 63 as suggested by @tscs37 fixes this issue. Cross compiling on Ubuntu and running on Windows has been tested and works now - even with multiple sub directories.
> Fixes #99 cross compile issue in walk function

- go.mod
- go.sum
As followup from #132 and kovacs/streamquote#1, consume a real release,
not a pseudo-version.
> consume nkovacs/streamquote release

- rice/flags.go
- rice/main.go
Allow sepcifying tags, and pass them to go/build.
> add --tags for build.AllTags

- README.md
`go get` is deprecated and should be replaced with go install
> Use go install instead of go get
